quarkus.http.port=8081

keycloak.server.url=${KEYCLOAK_SERVER_URL:http://localhost:8080}
keycloak.realm=${KEYCLOAK_REALM:user-management}

quarkus.keycloak.admin-client.server-url=${keycloak.server-url}
quarkus.keycloak.admin-client.realm=${keycloak.realm}
quarkus.keycloak.admin-client.client-id=${KEYCLOAK_ADMIN_CLIENT_ID:backend-keycloak-admin}
quarkus.keycloak.admin-client.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET}
quarkus.keycloak.admin-client.grant-type=CLIENT_CREDENTIALS

quarkus.oidc.auth-server-url=${keycloak.server-url}/realms/${keycloak.realm}
quarkus.oidc.client-id=${KEYCLOAK_OIDC_CLIENT_ID:backend-users}
quarkus.oidc.credentials.secret=${KEYCLOAK_OIDC_CLIENT_SECRET}

quarkus.smallrye-openapi.path=/openapi
