quarkus.http.port=8083
quarkus.http.root-path=/api

kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

mp.messaging.incoming.notification-commands.connector=smallrye-kafka
mp.messaging.incoming.notification-commands.topic=notification.commands
mp.messaging.incoming.notification-commands.group.id=backend-notification
mp.messaging.incoming.notification-commands.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.notification-commands.auto.offset.reset=earliest
mp.messaging.incoming.notification-commands.failure-strategy=dead-letter-queue
mp.messaging.incoming.notification-commands.dead-letter-queue.topic=notification.commands.dlq

mp.messaging.outgoing.notification-events.connector=smallrye-kafka
mp.messaging.outgoing.notification-events.topic=notification.events
mp.messaging.outgoing.notification-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.notification-events.acks=all

quarkus.mailer.from=${MAIL_FROM:no-reply@example.com}
quarkus.mailer.host=${MAIL_HOST:localhost}
quarkus.mailer.port=${MAIL_PORT:1025}
quarkus.mailer.username=${MAIL_USERNAME:}
quarkus.mailer.password=${MAIL_PASSWORD:}
quarkus.mailer.mock=${MAIL_MOCK:false}
