kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

mp.messaging.outgoing.identity-events.connector=smallrye-kafka
mp.messaging.outgoing.identity-events.topic=identity.events
mp.messaging.outgoing.identity-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.identity-events.acks=all
mp.messaging.outgoing.identity-events.enable.idempotence=true

mp.messaging.outgoing.notification-commands.connector=smallrye-kafka
mp.messaging.outgoing.notification-commands.topic=notification.commands
mp.messaging.outgoing.notification-commands.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.notification-commands.acks=all
mp.messaging.outgoing.notification-commands.enable.idempotence=true