quarkus.http.port=8081
quarkus.http.root-path=/api
quarkus.default-locale=en

keycloak.server-url=${KEYCLOAK_SERVER_URL:http://localhost:8080}
keycloak.realm=${KEYCLOAK_REALM}

quarkus.keycloak.admin-client.server-url=${keycloak.server-url}
quarkus.keycloak.admin-client.realm=${keycloak.realm}
quarkus.keycloak.admin-client.client-id=${KEYCLOAK_ADMIN_CLIENT_ID:backend-keycloak-admin}
quarkus.keycloak.admin-client.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET}
quarkus.keycloak.admin-client.grant-type=CLIENT_CREDENTIALS

quarkus.oidc.auth-server-url=${keycloak.server-url}/realms/${keycloak.realm}
quarkus.oidc.client-id=${KEYCLOAK_OIDC_CLIENT_ID:backend-users}
quarkus.oidc.credentials.secret=${KEYCLOAK_OIDC_CLIENT_SECRET}

quarkus.smallrye-openapi.path=/openapi
mp.openapi.scan.disable=true

quarkus.cache.caffeine."keycloak-user-attributes".expire-after-write=60S
quarkus.cache.caffeine."keycloak-client-uuids".expire-after-write=300S

identity.events.enabled=${IDENTITY_EVENTS_ENABLED:false}
notification.commands.enabled=${NOTIFICATION_COMMANDS_ENABLED:false}
notification.update-password.subject=${NOTIFICATION_UPDATE_PASSWORD_SUBJECT:Update your password}
notification.update-password.text-body=${NOTIFICATION_UPDATE_PASSWORD_TEXT_BODY:Hello {0}, an administrator requested a password update for your account. Access the application and follow the password update instructions.}
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
mp.messaging.outgoing.identity-events.connector=smallrye-kafka
mp.messaging.outgoing.identity-events.topic=identity.events
mp.messaging.outgoing.identity-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.identity-events.acks=all
mp.messaging.outgoing.identity-events.enable.idempotence=true
mp.messaging.outgoing.notification-commands.connector=smallrye-kafka
mp.messaging.outgoing.notification-commands.topic=notification.commands
mp.messaging.outgoing.notification-commands.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.notification-commands.acks=all
mp.messaging.outgoing.notification-commands.enable.idempotence=true
